import { useState, useEffect } from 'react';
import { Calendar, Users, BookOpen, Printer, Download, Filter, Settings2, X, AlertTriangle, CheckCircle, Loader2, UserMinus, RefreshCw } from 'lucide-react';
import api from '../api/axios';
import toast from 'react-hot-toast';
import Modal from '../components/ui/Modal';

const DAYS = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'];

export default function Reports() {
  const [tab, setTab] = useState('day-wise');
  const [timetables, setTimetables] = useState([]);
  const [classes, setClasses] = useState([]);
  const [teachers, setTeachers] = useState([]);
  const [selectedTT, setSelectedTT] = useState('');
  const [selectedDay, setSelectedDay] = useState('Monday');
  const [selectedClass, setSelectedClass] = useState('');
  const [selectedTeacher, setSelectedTeacher] = useState('');
  const [reportData, setReportData] = useState(null);
  const [loading, setLoading] = useState(false);
  const [maxPeriod, setMaxPeriod] = useState(8);

  // Replacement report
  const [replacementDate, setReplacementDate] = useState(new Date().toISOString().split('T')[0]);
  const [replacementDateTo, setReplacementDateTo] = useState('');
  const [replacementTeacher, setReplacementTeacher] = useState('');
  const [replacementData, setReplacementData] = useState(null);

  const [showPrintModal, setShowPrintModal] = useState(false);
  const [printConfig, setPrintConfig] = useState({
    size: 'print-a4',
    orientation: 'print-landscape',
    colorMode: 'print-color',
    nameFormat: 'full',
    headerText: 'School Timetable Report',
    footerText: 'Generated by TimeCraft Advanced System',
    fontSize: 'normal'
  });

  useEffect(() => {
    Promise.all([
      api.get('/timetable/list').then(r => { const d = r.data?.data || r.data || []; setTimetables(d); if (d.length) setSelectedTT(d[0]._id); }),
      api.get('/classes').then(r => { const d = r.data?.data || r.data || []; setClasses(d); if (d.length) setSelectedClass(d[0]._id); }),
      api.get('/teachers').then(r => { const d = r.data?.data || r.data || []; setTeachers(d); if (d.length) setSelectedTeacher(d[0]._id); })
    ]);
  }, []);

  const fetchReport = async () => {
    if (tab === 'replacement') {
      fetchReplacementReport();
      return;
    }
    if (!selectedTT) return toast.error('Select a timetable');
    setLoading(true);
    try {
      let r;
      if (tab === 'day-wise') {
        r = await api.get(`/reports/day-wise?timetableId=${selectedTT}&day=${selectedDay}`);
        setReportData(r.data?.data || r.data);
      } else if (tab === 'class-weekly') {
        if (!selectedClass) return toast.error('Select a class');
        r = await api.get(`/reports/class-weekly/${selectedClass}?timetableId=${selectedTT}`);
        const d = r.data?.data || r.data;
        setReportData(d); setMaxPeriod(d?.maxPeriod || 8);
      } else {
        if (!selectedTeacher) return toast.error('Select a teacher');
        r = await api.get(`/reports/teacher-weekly/${selectedTeacher}?timetableId=${selectedTT}`);
        const d = r.data?.data || r.data;
        setReportData(d); setMaxPeriod(d?.maxPeriod || 8);
      }
    } catch (err) { toast.error(err.response?.data?.error || 'Failed to load report'); }
    finally { setLoading(false); }
  };

  const fetchReplacementReport = async () => {
    setLoading(true);
    try {
      let url = `/reports/replacement-report?date=${replacementDate}`;
      if (replacementDateTo) url += `&from=${replacementDate}&to=${replacementDateTo}`;
      if (replacementTeacher) url += `&teacherId=${replacementTeacher}`;
      const r = await api.get(url);
      setReplacementData(r.data?.data || r.data);
    } catch (err) { toast.error('Failed to load replacement report'); }
    finally { setLoading(false); }
  };

  useEffect(() => {
    if (tab === 'replacement') fetchReplacementReport();
    else if (selectedTT) fetchReport();
  }, [tab, selectedTT, selectedDay, selectedClass, selectedTeacher]);

  const exportCSV = () => {
    let csv = '';
    if (tab === 'replacement' && replacementData) {
      csv = 'Period,Original Teacher,Substitute,Class,Subject,Status\n';
      replacementData.substitutions?.forEach(s => {
        csv += `P${s.period},${s.originalTeacher?.name || ''},${s.substituteTeacher?.name || ''},${s.class?.name || ''},${s.subject?.name || ''},Active\n`;
      });
    } else if (tab === 'day-wise' && reportData?.report) {
      csv = 'Class,' + Array.from({ length: 10 }, (_, i) => `P${i + 1}`).join(',') + '\n';
      reportData.report.forEach(cr => {
        const row = [cr.class.name];
        for (let p = 1; p <= 10; p++) {
          const slot = cr.periods.find(s => s.period === p);
          row.push(slot?.subject?.name || (slot?.type === 'reserved' ? 'Break' : ''));
        }
        csv += row.join(',') + '\n';
      });
    } else if (reportData?.schedule) {
      csv = 'Period,' + DAYS.join(',') + '\n';
      for (let p = 1; p <= maxPeriod; p++) {
        const row = [`P${p}`];
        DAYS.forEach(d => {
          const slot = reportData.schedule[d]?.find(s => s.period === p);
          row.push(slot?.subject?.name || '');
        });
        csv += row.join(',') + '\n';
      }
    }
    if (!csv) return toast.error('No data to export');
    const blob = new Blob([csv], { type: 'text/csv' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a'); a.href = url; a.download = `report_${tab}.csv`; a.click();
    URL.revokeObjectURL(url);
  };

  const downloadPDF = async () => {
    try {
      let url = '';
      if (tab === 'class-weekly' && selectedClass) {
        url = `/export/timetable/pdf?timetableId=${selectedTT}&classId=${selectedClass}`;
      } else if (tab === 'teacher-weekly' && selectedTeacher) {
        url = `/export/timetable/teacher-pdf?timetableId=${selectedTT}&teacherId=${selectedTeacher}`;
      } else if (tab === 'day-wise') {
        url = `/export/timetable/pdf?timetableId=${selectedTT}`;
      } else if (tab === 'replacement') {
        url = `/export/daily-sheet/pdf?date=${replacementDate}`;
      } else {
        return toast.error('Select a valid report to export');
      }
      toast.loading('Generating PDF...', { id: 'pdf' });
      const res = await api.get(url, { responseType: 'blob' });
      const blob = new Blob([res.data], { type: 'application/pdf' });
      const link = document.createElement('a');
      link.href = URL.createObjectURL(blob);
      link.download = `report_${tab}_${Date.now()}.pdf`;
      link.click();
      URL.revokeObjectURL(link.href);
      toast.success('PDF downloaded!', { id: 'pdf' });
    } catch (err) { toast.error('PDF export failed: ' + (err.response?.data?.error || err.message), { id: 'pdf' }); }
  };

  const handlePrint = () => {
    const nameClass = printConfig.nameFormat === 'alias' ? 'use-alias' : printConfig.nameFormat === 'short' ? 'use-short-name' : '';
    const fontClass = printConfig.fontSize === 'small' ? 'print-font-small' : printConfig.fontSize === 'large' ? 'print-font-large' : '';
    document.body.className = `${printConfig.size} ${printConfig.orientation} ${printConfig.colorMode} ${nameClass} ${fontClass}`;
    window.print();
    setTimeout(() => { document.body.className = ''; }, 1000);
    setShowPrintModal(false);
  };

  const tabs = [
    { id: 'day-wise', label: 'Day-Wise', icon: Calendar },
    { id: 'class-weekly', label: 'Class Weekly', icon: BookOpen },
    { id: 'teacher-weekly', label: 'Teacher Weekly', icon: Users },
    { id: 'replacement', label: 'Replacement', icon: UserMinus }
  ];

  return (
    <div className="space-y-5 animate-fade-in relative">
      {/* Print header */}
      <div className="print-header">
        <h2>{printConfig.headerText}</h2>
      </div>

      <div className="flex items-center justify-between flex-wrap gap-3 no-print">
        <div><h1 className="page-title">Reports</h1><p className="page-subtitle">Generate, view, and export timetable reports</p></div>
        <div className="flex gap-2">
          <button onClick={() => setShowPrintModal(true)} className="btn-secondary flex items-center gap-2 text-sm"><Printer size={14} /> Print</button>
          <button onClick={downloadPDF} className="btn-secondary flex items-center gap-2 text-sm"><Download size={14} /> PDF</button>
          <button onClick={exportCSV} className="btn-primary flex items-center gap-2 text-sm"><Download size={14} /> CSV</button>
        </div>
      </div>

      {/* Tabs */}
      <div className="glass-card p-1.5 flex gap-1 no-print overflow-x-auto">
        {tabs.map(t => {
          const Icon = t.icon;
          return (
            <button key={t.id} onClick={() => setTab(t.id)}
              className={`flex-1 flex items-center justify-center gap-2 px-3 py-2.5 rounded-xl text-sm font-medium transition-all whitespace-nowrap min-w-[100px]
                ${tab === t.id ? 'bg-primary-600 text-white shadow-lg shadow-primary-600/30' : 'text-slate-500 dark:text-dark-400 hover:text-slate-900 dark:hover:text-dark-50 hover:bg-slate-100 dark:hover:bg-dark-800/60'}`}>
              <Icon size={15} />{t.label}
            </button>
          );
        })}
      </div>

      {/* Filters */}
      <div className="glass-card p-4 flex flex-wrap gap-3 items-end no-print">
        {tab !== 'replacement' && (
          <div className="min-w-[180px]">
            <label className="text-xs text-slate-500 dark:text-dark-400 mb-1 block">Timetable</label>
            <select value={selectedTT} onChange={e => setSelectedTT(e.target.value)} className="select-field text-sm">
              {timetables.map(t => <option key={t._id} value={t._id}>{t.name} ({t.status})</option>)}
            </select>
          </div>
        )}
        {tab === 'day-wise' && (
          <div className="min-w-[140px]">
            <label className="text-xs text-slate-500 dark:text-dark-400 mb-1 block">Day</label>
            <select value={selectedDay} onChange={e => setSelectedDay(e.target.value)} className="select-field text-sm">
              {DAYS.map(d => <option key={d} value={d}>{d}</option>)}
            </select>
          </div>
        )}
        {tab === 'class-weekly' && (
          <div className="min-w-[160px]">
            <label className="text-xs text-slate-500 dark:text-dark-400 mb-1 block">Class</label>
            <select value={selectedClass} onChange={e => setSelectedClass(e.target.value)} className="select-field text-sm">
              {classes.map(c => <option key={c._id} value={c._id}>{c.name}</option>)}
            </select>
          </div>
        )}
        {tab === 'teacher-weekly' && (
          <div className="min-w-[180px]">
            <label className="text-xs text-slate-500 dark:text-dark-400 mb-1 block">Teacher</label>
            <select value={selectedTeacher} onChange={e => setSelectedTeacher(e.target.value)} className="select-field text-sm">
              {teachers.map(t => <option key={t._id} value={t._id}>{t.name}</option>)}
            </select>
          </div>
        )}
        {tab === 'replacement' && (
          <>
            <div className="min-w-[130px]">
              <label className="text-xs text-slate-500 dark:text-dark-400 mb-1 block">From Date</label>
              <input type="date" value={replacementDate} onChange={e => setReplacementDate(e.target.value)} className="input-field text-sm" />
            </div>
            <div className="min-w-[130px]">
              <label className="text-xs text-slate-500 dark:text-dark-400 mb-1 block">To Date (optional)</label>
              <input type="date" value={replacementDateTo} onChange={e => setReplacementDateTo(e.target.value)} className="input-field text-sm" />
            </div>
            <div className="min-w-[160px]">
              <label className="text-xs text-slate-500 dark:text-dark-400 mb-1 block">Teacher (optional)</label>
              <select value={replacementTeacher} onChange={e => setReplacementTeacher(e.target.value)} className="select-field text-sm">
                <option value="">All Teachers</option>
                {teachers.map(t => <option key={t._id} value={t._id}>{t.name}</option>)}
              </select>
            </div>
          </>
        )}
        <button onClick={fetchReport} className="btn-secondary flex items-center gap-2 text-sm"><RefreshCw size={14} /> Refresh</button>
      </div>

      {/* Report Content */}
      {loading ? (
        <div className="glass-card p-16 text-center"><Loader2 className="animate-spin text-primary-500 mx-auto" size={24} /></div>
      ) : tab === 'replacement' ? (
        <ReplacementReport data={replacementData} />
      ) : !reportData ? (
        <div className="glass-card p-16 text-center text-slate-400 dark:text-dark-500">Select filters and generate a report</div>
      ) : tab === 'day-wise' ? (
        <DayWiseReport data={reportData} />
      ) : tab === 'class-weekly' ? (
        <WeeklyGridReport data={reportData} maxPeriod={maxPeriod} type="class" />
      ) : (
        <WeeklyGridReport data={reportData} maxPeriod={maxPeriod} type="teacher" />
      )}

      {/* Print footer */}
      <div className="print-footer">
        {printConfig.footerText} | Printed on {new Date().toLocaleDateString()}
      </div>

      {/* Print Settings Modal */}
      {showPrintModal && (
        <Modal isOpen={showPrintModal} onClose={() => setShowPrintModal(false)} title="Advanced Print Setup">
          <div className="space-y-4">
            <div className="grid grid-cols-2 gap-4">
              <div>
                <label className="text-xs text-slate-500 dark:text-dark-400 mb-1 block font-medium">Paper Size</label>
                <select className="select-field text-sm" value={printConfig.size} onChange={e => setPrintConfig({...printConfig, size: e.target.value})}>
                  <option value="print-a4">A4 (210 × 297mm)</option>
                  <option value="print-a3">A3 (297 × 420mm)</option>
                  <option value="print-letter">Letter (8.5 × 11")</option>
                  <option value="print-legal">Legal (8.5 × 14")</option>
                </select>
              </div>
              <div>
                <label className="text-xs text-slate-500 dark:text-dark-400 mb-1 block font-medium">Orientation</label>
                <select className="select-field text-sm" value={printConfig.orientation} onChange={e => setPrintConfig({...printConfig, orientation: e.target.value})}>
                  <option value="print-landscape">Landscape</option>
                  <option value="print-portrait">Portrait</option>
                </select>
              </div>
              <div>
                <label className="text-xs text-slate-500 dark:text-dark-400 mb-1 block font-medium">Color Mode</label>
                <select className="select-field text-sm" value={printConfig.colorMode} onChange={e => setPrintConfig({...printConfig, colorMode: e.target.value})}>
                  <option value="print-color">Colorful (Default)</option>
                  <option value="print-bw">Black & White</option>
                  <option value="print-contrast">High Contrast</option>
                </select>
              </div>
              <div>
                <label className="text-xs text-slate-500 dark:text-dark-400 mb-1 block font-medium">Teacher Names</label>
                <select className="select-field text-sm" value={printConfig.nameFormat} onChange={e => setPrintConfig({...printConfig, nameFormat: e.target.value})}>
                  <option value="full">Full Name</option>
                  <option value="short">Short Name</option>
                  <option value="alias">Print Alias</option>
                </select>
              </div>
              <div>
                <label className="text-xs text-slate-500 dark:text-dark-400 mb-1 block font-medium">Font Size</label>
                <select className="select-field text-sm" value={printConfig.fontSize} onChange={e => setPrintConfig({...printConfig, fontSize: e.target.value})}>
                  <option value="small">Small (compact)</option>
                  <option value="normal">Normal</option>
                  <option value="large">Large (readable)</option>
                </select>
              </div>
            </div>

            <div>
              <label className="text-xs text-slate-500 dark:text-dark-400 mb-1 block font-medium">School Branding Header</label>
              <input type="text" className="input-field text-sm" value={printConfig.headerText} onChange={e => setPrintConfig({...printConfig, headerText: e.target.value})} placeholder="e.g., Delhi Public School - Timetable Report" />
            </div>
            <div>
              <label className="text-xs text-slate-500 dark:text-dark-400 mb-1 block font-medium">Footer Text</label>
              <input type="text" className="input-field text-sm" value={printConfig.footerText} onChange={e => setPrintConfig({...printConfig, footerText: e.target.value})} />
            </div>

            {/* Preview */}
            <div className="p-3 bg-slate-50 dark:bg-dark-800/50 rounded-xl border border-slate-200 dark:border-dark-700">
              <p className="text-[10px] text-slate-400 dark:text-dark-500 mb-1 font-medium">Preview</p>
              <div className="bg-white dark:bg-dark-900 border border-slate-200 dark:border-dark-700 rounded-lg p-3 text-center" style={{ maxWidth: printConfig.orientation === 'print-landscape' ? '200px' : '140px', aspectRatio: printConfig.orientation === 'print-landscape' ? '1.4/1' : '1/1.4' }}>
                <p className="text-[8px] font-bold border-b border-slate-200 pb-1 mb-1">{printConfig.headerText}</p>
                <div className="flex gap-0.5 justify-center">
                  {[1,2,3].map(i => <div key={i} className="w-3 h-1 bg-slate-200 rounded" />)}
                </div>
                <p className="text-[6px] text-slate-400 mt-1 border-t border-slate-200 pt-0.5">{printConfig.footerText}</p>
              </div>
            </div>

            <div className="flex justify-end gap-3">
              <button onClick={() => setShowPrintModal(false)} className="btn-secondary text-sm">Cancel</button>
              <button onClick={handlePrint} className="btn-primary flex items-center gap-2 text-sm"><Printer size={14} /> Print</button>
            </div>
          </div>
        </Modal>
      )}
    </div>
  );
}

function ReplacementReport({ data }) {
  if (!data) return <div className="glass-card p-16 text-center text-slate-400 dark:text-dark-500">Select a date to view replacement report</div>;

  return (
    <div className="space-y-4">
      {/* Summary cards */}
      <div className="grid grid-cols-2 sm:grid-cols-4 gap-3">
        <div className="glass-card p-4 text-center">
          <p className="text-2xl font-bold text-slate-800 dark:text-dark-100">{data.summary?.totalAbsences || 0}</p>
          <p className="text-[10px] text-slate-500 dark:text-dark-400">Total Absences</p>
        </div>
        <div className="glass-card p-4 text-center">
          <p className="text-2xl font-bold text-emerald-500">{data.summary?.fullyResolved || 0}</p>
          <p className="text-[10px] text-slate-500 dark:text-dark-400">Resolved</p>
        </div>
        <div className="glass-card p-4 text-center">
          <p className="text-2xl font-bold text-amber-500">{data.summary?.partiallyResolved || 0}</p>
          <p className="text-[10px] text-slate-500 dark:text-dark-400">Partial</p>
        </div>
        <div className="glass-card p-4 text-center">
          <p className="text-2xl font-bold text-red-500">{data.unresolvedCount || 0}</p>
          <p className="text-[10px] text-slate-500 dark:text-dark-400">Unresolved Periods</p>
        </div>
      </div>

      {/* Substitutions list */}
      {data.substitutions?.length > 0 && (
        <div className="glass-card overflow-hidden">
          <div className="px-4 py-3 border-b border-slate-200 dark:border-dark-700/50">
            <p className="text-sm font-semibold text-slate-800 dark:text-dark-100">Substitutions ({data.totalReplacements})</p>
          </div>
          <div className="overflow-x-auto">
            <table className="w-full print-table">
              <thead><tr className="table-header">
                <th className="p-3 text-left text-xs">Period</th>
                <th className="p-3 text-left text-xs">Original Teacher</th>
                <th className="p-3 text-center text-xs">→</th>
                <th className="p-3 text-left text-xs">Substitute</th>
                <th className="p-3 text-left text-xs">Class</th>
                <th className="p-3 text-left text-xs">Subject</th>
              </tr></thead>
              <tbody>
                {data.substitutions.map((s, i) => (
                  <tr key={i} className="table-row">
                    <td className="p-3 text-xs font-medium text-slate-800 dark:text-dark-100">P{s.period}</td>
                    <td className="p-3 text-xs text-slate-600 dark:text-dark-300">{s.originalTeacher?.name || '—'}</td>
                    <td className="p-3 text-center text-primary-500">→</td>
                    <td className="p-3 text-xs font-medium text-emerald-600 dark:text-emerald-400">{s.substituteTeacher?.name || '—'}</td>
                    <td className="p-3 text-xs text-slate-600 dark:text-dark-300">{s.class?.name || '—'}</td>
                    <td className="p-3 text-xs">
                      <span className="px-2 py-0.5 rounded-full text-[10px]" style={{ backgroundColor: (s.subject?.color || '#6366f1') + '20', color: s.subject?.color || '#6366f1' }}>
                        {s.subject?.name || '—'}
                      </span>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>
      )}

      {/* Absences detail */}
      {data.absences?.length > 0 && (
        <div className="glass-card p-4">
          <p className="text-sm font-semibold text-slate-800 dark:text-dark-100 mb-3">Absent Teachers</p>
          <div className="space-y-2">
            {data.absences.map((a, i) => (
              <div key={i} className="flex items-center gap-3 p-3 rounded-xl bg-slate-50 dark:bg-dark-800/50">
                <UserMinus size={16} className={a.status === 'resolved' ? 'text-emerald-500' : 'text-red-500'} />
                <div className="flex-1">
                  <p className="text-sm font-medium text-slate-800 dark:text-dark-100">{a.teacher?.name}</p>
                  <p className="text-[10px] text-slate-400">{a.affectedBlocks?.length || 0} affected periods · {a.reason || 'No reason specified'}</p>
                </div>
                <span className={`badge border text-[10px] ${a.status === 'resolved' ? 'badge-success' : a.status === 'partial' ? 'badge-warning' : 'badge-danger'}`}>
                  {a.status}
                </span>
              </div>
            ))}
          </div>
        </div>
      )}

      {data.substitutions?.length === 0 && data.absences?.length === 0 && (
        <div className="glass-card p-12 text-center text-slate-400 dark:text-dark-500">No absences or substitutions recorded for this date</div>
      )}
    </div>
  );
}

function DayWiseReport({ data }) {
  if (!data?.report?.length) return <div className="glass-card p-12 text-center text-slate-400 dark:text-dark-500">No data for this day</div>;
  const summary = data.summary || {};
  return (
    <div className="space-y-3">
      {/* Summary banner */}
      <div className="grid grid-cols-2 sm:grid-cols-4 gap-3">
        <div className="glass-card p-4 text-center">
          <p className="text-2xl font-bold text-slate-800 dark:text-dark-100">{data.classCount}</p>
          <p className="text-[10px] text-slate-500 dark:text-dark-400">Classes</p>
        </div>
        <div className="glass-card p-4 text-center">
          <p className="text-2xl font-bold text-primary-500">{summary.totalSchedulablePeriods || 8}</p>
          <p className="text-[10px] text-slate-500 dark:text-dark-400">Periods per Class</p>
        </div>
        <div className="glass-card p-4 text-center">
          <p className="text-2xl font-bold text-emerald-500">{summary.totalAssignedAcrossClasses || 0}</p>
          <p className="text-[10px] text-slate-500 dark:text-dark-400">Total Assigned</p>
        </div>
        <div className="glass-card p-4 text-center">
          <p className={`text-2xl font-bold ${(summary.overallCoverage || 0) >= 90 ? 'text-emerald-500' : (summary.overallCoverage || 0) >= 70 ? 'text-amber-500' : 'text-red-500'}`}>{summary.overallCoverage || 0}%</p>
          <p className="text-[10px] text-slate-500 dark:text-dark-400">Overall Coverage</p>
        </div>
      </div>

      <p className="text-sm text-slate-500 dark:text-dark-400">{data.day} — {data.classCount} classes</p>
      {data.report.map(cr => (
        <div key={cr.class._id} className="glass-card p-4">
          <div className="flex items-center justify-between mb-2">
            <p className="text-sm font-semibold text-slate-800 dark:text-dark-100">{cr.class.name}</p>
            <div className="flex items-center gap-2">
              <span className={`text-xs font-medium ${cr.coveragePercent >= 90 ? 'text-emerald-500' : cr.coveragePercent >= 70 ? 'text-amber-500' : 'text-red-500'}`}>
                {cr.assignedPeriods}/{cr.totalSchedulablePeriods} ({cr.coveragePercent}%)
              </span>
              <div className="w-16 h-1.5 bg-slate-200 dark:bg-dark-700 rounded-full overflow-hidden">
                <div className={`h-full rounded-full ${cr.coveragePercent >= 90 ? 'bg-emerald-500' : cr.coveragePercent >= 70 ? 'bg-amber-500' : 'bg-red-500'}`}
                  style={{ width: `${Math.min(100, cr.coveragePercent)}%` }} />
              </div>
            </div>
          </div>
          <div className="flex flex-wrap gap-1.5">
            {cr.periods.map((slot, i) => (
              <div key={i} className="px-3 py-2 rounded-lg text-xs min-w-[80px] border"
                style={{
                  borderColor: slot.subject?.color ? `${slot.subject.color}40` : '#e2e8f0',
                  background: slot.subject?.color ? `${slot.subject.color}12` : slot.type === 'reserved' ? '#fef3c7' : '#f8fafc'
                }}>
                <p className="font-medium" style={{ color: slot.subject?.color || '#64748b' }}>
                  <span className="full-name">{slot.subject?.name || (slot.type === 'reserved' ? '☕ Break' : `P${slot.period}`)}</span>
                  <span className="print-alias">{slot.subject?.shortName || slot.subject?.name?.slice(0,3) || '—'}</span>
                </p>
                {slot.teacher && (
                  <p className="text-slate-500 dark:text-dark-400 text-[10px]">
                    <span className="full-name">{slot.teacher.name}</span>
                    <span className="print-alias">{slot.teacher.shortName || slot.teacher.printAlias || slot.teacher.name?.split(' ')[0]}</span>
                  </p>
                )}
                {slot.room && <p className="text-slate-400 text-[10px]">{slot.room.name}</p>}
              </div>
            ))}
          </div>
        </div>
      ))}
    </div>
  );
}

function WeeklyGridReport({ data, maxPeriod, type }) {
  const schedule = data?.schedule || {};
  const title = type === 'class' ? data?.class?.name : data?.teacher?.name;
  return (
    <div className="glass-card overflow-hidden">
      {title && <div className="px-4 py-3 border-b border-slate-200 dark:border-dark-700/50">
        <p className="text-sm font-semibold text-slate-800 dark:text-dark-100">{title}</p>
        {type === 'teacher' && <p className="text-xs text-slate-500 dark:text-dark-400">{data.totalPeriods} teaching periods this week</p>}
      </div>}
      <div className="overflow-x-auto print-table-wrapper">
        <table className="w-full min-w-[700px] print-table">
          <thead>
            <tr className="table-header">
              <th className="p-3 text-left w-20 text-xs">Period</th>
              {DAYS.map(d => <th key={d} className="p-3 text-center text-xs">{d.slice(0, 3)}</th>)}
            </tr>
          </thead>
          <tbody>
            {Array.from({ length: maxPeriod }, (_, i) => i + 1).map(p => (
              <tr key={p} className="table-row">
                <td className="p-3 text-xs font-medium text-slate-600 dark:text-dark-300">P{p}</td>
                {DAYS.map(d => {
                  const slot = schedule[d]?.find(s => s.period === p);
                  if (!slot) return <td key={d} className="p-3 text-center text-slate-300 dark:text-dark-600 text-xs">—</td>;
                  if (slot.type === 'reserved' && !slot.subject) {
                    return <td key={d} className="p-3 text-center bg-amber-50 dark:bg-dark-800/30 text-amber-500 text-xs">Break</td>;
                  }
                  return (
                    <td key={d} className="p-2 text-center" style={{ borderLeft: slot.subject?.color ? `3px solid ${slot.subject.color}` : undefined }}>
                      <p className="text-xs font-medium text-slate-800 dark:text-dark-100">
                        <span className="full-name">{slot.subject?.name || '—'}</span>
                        <span className="print-alias">{slot.subject?.shortName || slot.subject?.name?.slice(0,3) || '—'}</span>
                      </p>
                      {type === 'class' && slot.teacher && (
                        <p className="text-[10px] text-slate-500 dark:text-dark-400 mt-0.5">
                          <span className="full-name">{slot.teacher.name}</span>
                          <span className="print-alias">{slot.teacher.shortName || slot.teacher.name?.split(' ')[0]}</span>
                        </p>
                      )}
                      {type === 'teacher' && slot.classes && <p className="text-[10px] text-slate-500 dark:text-dark-400">{slot.classes.map(c => c.name).join(', ')}</p>}
                      {slot.room && <p className="text-[10px] text-slate-400 dark:text-dark-500">{slot.room.name}</p>}
                    </td>
                  );
                })}
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </div>
  );
}
