const { jsPDF } = require('jspdf');
const autoTablePlugin = require('jspdf-autotable');
// Register the autoTable plugin on jsPDF (Node.js compatibility)
if (typeof autoTablePlugin.applyPlugin === 'function') {
  autoTablePlugin.applyPlugin(jsPDF);
}

const DAYS_ORDER = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'];
const DAY_SHORT = { Monday: 'Mon', Tuesday: 'Tue', Wednesday: 'Wed', Thursday: 'Thu', Friday: 'Fri', Saturday: 'Sat' };

class PDFExporter {
  constructor(school, session) {
    this.school = school;
    this.session = session;
  }

  _createDoc(orientation = 'landscape') {
    const doc = new jsPDF({ orientation, unit: 'mm', format: 'a4' });
    doc.setFont('helvetica');
    return doc;
  }

  _addHeader(doc, title, subtitle) {
    const pageWidth = doc.internal.pageSize.getWidth();
    // School branding
    doc.setFontSize(16);
    doc.setFont('helvetica', 'bold');
    doc.text(this.school?.name || 'School Timetable', pageWidth / 2, 12, { align: 'center' });
    doc.setFontSize(9);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(100);
    const schoolInfo = [this.school?.code, this.school?.email, this.school?.phone].filter(Boolean).join(' | ');
    if (schoolInfo) doc.text(schoolInfo, pageWidth / 2, 17, { align: 'center' });

    // Session info
    if (this.session?.name) {
      doc.text(`Session: ${this.session.name}`, pageWidth / 2, 21, { align: 'center' });
    }

    // Title
    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(50);
    doc.text(title, pageWidth / 2, 28, { align: 'center' });

    if (subtitle) {
      doc.setFontSize(9);
      doc.setFont('helvetica', 'normal');
      doc.setTextColor(120);
      doc.text(subtitle, pageWidth / 2, 33, { align: 'center' });
    }

    // Date
    doc.setFontSize(7);
    doc.setTextColor(150);
    doc.text(`Generated: ${new Date().toLocaleString('en-IN')}`, pageWidth - 10, 8, { align: 'right' });

    doc.setTextColor(0);
    return 36;
  }

  _addFooter(doc) {
    const pageCount = doc.internal.getNumberOfPages();
    for (let i = 1; i <= pageCount; i++) {
      doc.setPage(i);
      const pageHeight = doc.internal.pageSize.getHeight();
      const pageWidth = doc.internal.pageSize.getWidth();
      doc.setFontSize(7);
      doc.setTextColor(150);
      doc.text('Generated by TimeCraft ERP', 10, pageHeight - 5);
      doc.text(`Page ${i} of ${pageCount}`, pageWidth - 10, pageHeight - 5, { align: 'right' });
    }
  }

  // ── Class Timetable PDF ──
  generateClassTimetable(classInfo, blocks, workingDays, totalPeriods) {
    const doc = this._createDoc('landscape');
    const startY = this._addHeader(doc, `Class Timetable: ${classInfo.name}`, `Grade ${classInfo.grade} - Section ${classInfo.section || ''}`);

    const days = workingDays || DAYS_ORDER.slice(0, 6);
    const headers = ['Period', ...days.map(d => DAY_SHORT[d] || d)];

    const rows = [];
    for (let p = 1; p <= totalPeriods; p++) {
      const row = [`P${p}`];
      for (const day of days) {
        const block = blocks.find(b => b.day === day && b.periods?.includes(p));
        if (block) {
          const parts = [block.subject?.name || ''];
          if (block.teacher?.shortName || block.teacher?.name) parts.push(block.teacher.shortName || block.teacher.name);
          if (block.room?.name) parts.push(block.room.name);
          row.push(parts.join('\n'));
        } else {
          row.push('-');
        }
      }
      rows.push(row);
    }

    doc.autoTable({
      head: [headers],
      body: rows,
      startY,
      theme: 'grid',
      styles: { fontSize: 8, cellPadding: 2, halign: 'center', valign: 'middle', lineWidth: 0.1 },
      headStyles: { fillColor: [67, 56, 202], textColor: 255, fontStyle: 'bold', fontSize: 8 },
      alternateRowStyles: { fillColor: [245, 245, 255] },
      columnStyles: { 0: { fontStyle: 'bold', cellWidth: 16 } },
      margin: { top: startY, left: 8, right: 8 }
    });

    this._addFooter(doc);
    return doc.output('arraybuffer');
  }

  // ── Teacher Timetable PDF ──
  generateTeacherTimetable(teacherInfo, blocks, workingDays, totalPeriods) {
    const doc = this._createDoc('landscape');
    const startY = this._addHeader(doc, `Teacher Timetable: ${teacherInfo.name}`, `Department: ${teacherInfo.department || 'General'}`);

    const days = workingDays || DAYS_ORDER.slice(0, 6);
    const headers = ['Period', ...days.map(d => DAY_SHORT[d] || d)];

    const rows = [];
    for (let p = 1; p <= totalPeriods; p++) {
      const row = [`P${p}`];
      for (const day of days) {
        const block = blocks.find(b => b.day === day && b.periods?.includes(p));
        if (block) {
          const parts = [block.subject?.name || ''];
          if (block.classes?.length) parts.push(block.classes.map(c => c.name).join('+'));
          if (block.room?.name) parts.push(block.room.name);
          row.push(parts.join('\n'));
        } else {
          row.push('FREE');
        }
      }
      rows.push(row);
    }

    doc.autoTable({
      head: [headers],
      body: rows,
      startY,
      theme: 'grid',
      styles: { fontSize: 8, cellPadding: 2, halign: 'center', valign: 'middle', lineWidth: 0.1 },
      headStyles: { fillColor: [16, 185, 129], textColor: 255, fontStyle: 'bold', fontSize: 8 },
      alternateRowStyles: { fillColor: [240, 253, 244] },
      columnStyles: { 0: { fontStyle: 'bold', cellWidth: 16 } },
      margin: { top: startY, left: 8, right: 8 }
    });

    this._addFooter(doc);
    return doc.output('arraybuffer');
  }

  // ── Daily Substitution Sheet PDF ──
  generateDailySheet(date, substitutions, absences) {
    const doc = this._createDoc('portrait');
    const dateStr = new Date(date).toLocaleDateString('en-IN', { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' });
    const startY = this._addHeader(doc, 'Daily Substitution Sheet', dateStr);

    if (absences?.length > 0) {
      doc.setFontSize(10);
      doc.setFont('helvetica', 'bold');
      doc.text('Absent Teachers:', 10, startY + 4);
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(8);
      absences.forEach((a, i) => {
        doc.text(`• ${a.teacher?.name || 'Unknown'} — ${a.reason || 'No reason'}`, 14, startY + 10 + (i * 5));
      });
    }

    const absenceOffset = absences?.length ? (absences.length * 5 + 16) : 4;
    const headers = ['Period', 'Class', 'Subject', 'Original Teacher', 'Substitute', 'Status'];
    const rows = (substitutions || []).map(s => [
      `P${s.period}`,
      s.class?.name || '',
      s.subject?.name || '',
      s.originalTeacher?.name || '',
      s.substituteTeacher?.name || '',
      s.status || 'pending'
    ]);

    if (rows.length === 0) {
      rows.push(['—', '—', 'No substitutions for this date', '—', '—', '—']);
    }

    doc.autoTable({
      head: [headers],
      body: rows,
      startY: startY + absenceOffset,
      theme: 'grid',
      styles: { fontSize: 8, cellPadding: 2, halign: 'center', valign: 'middle' },
      headStyles: { fillColor: [234, 88, 12], textColor: 255, fontStyle: 'bold' },
      margin: { left: 10, right: 10 }
    });

    this._addFooter(doc);
    return doc.output('arraybuffer');
  }

  // ── Teacher Workload PDF ──
  generateWorkloadReport(workloadData) {
    const doc = this._createDoc('landscape');
    const startY = this._addHeader(doc, 'Teacher Workload Report', `Total Teachers: ${workloadData?.length || 0}`);

    const headers = ['Teacher', 'Dept', 'Max/Day', 'Max/Week', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Total', 'Load %', 'Status'];
    const rows = (workloadData || []).map(w => [
      w.teacher?.name || '',
      w.teacher?.department || '',
      w.maxPerDay || 0,
      w.maxPerWeek || 0,
      w.dayLoads?.Monday || 0,
      w.dayLoads?.Tuesday || 0,
      w.dayLoads?.Wednesday || 0,
      w.dayLoads?.Thursday || 0,
      w.dayLoads?.Friday || 0,
      w.dayLoads?.Saturday || 0,
      w.totalPeriods || 0,
      `${w.utilization || 0}%`,
      w.status || ''
    ]);

    doc.autoTable({
      head: [headers],
      body: rows,
      startY,
      theme: 'grid',
      styles: { fontSize: 7, cellPadding: 1.5, halign: 'center', valign: 'middle' },
      headStyles: { fillColor: [99, 102, 241], textColor: 255, fontStyle: 'bold', fontSize: 7 },
      columnStyles: { 0: { halign: 'left', cellWidth: 30 }, 1: { halign: 'left' } },
      margin: { left: 6, right: 6 }
    });

    this._addFooter(doc);
    return doc.output('arraybuffer');
  }

  // ── Full School Timetable PDF (all classes) ──
  generateFullSchoolPDF(classReports, workingDays, totalPeriods) {
    const doc = this._createDoc('landscape');
    const days = workingDays || DAYS_ORDER.slice(0, 6);

    classReports.forEach((cr, idx) => {
      if (idx > 0) doc.addPage();
      const startY = this._addHeader(doc, `Class: ${cr.class?.name || 'Unknown'}`, '');
      const headers = ['Period', ...days.map(d => DAY_SHORT[d] || d)];
      const rows = [];
      for (let p = 1; p <= totalPeriods; p++) {
        const row = [`P${p}`];
        for (const day of days) {
          const entries = cr.schedule?.[day] || [];
          const entry = entries.find(e => e.period === p);
          row.push(entry ? `${entry.subject || ''}\n${entry.teacher || ''}` : '-');
        }
        rows.push(row);
      }

      doc.autoTable({
        head: [headers],
        body: rows,
        startY,
        theme: 'grid',
        styles: { fontSize: 7, cellPadding: 2, halign: 'center', valign: 'middle', lineWidth: 0.1 },
        headStyles: { fillColor: [67, 56, 202], textColor: 255, fontStyle: 'bold', fontSize: 7 },
        alternateRowStyles: { fillColor: [245, 245, 255] },
        columnStyles: { 0: { fontStyle: 'bold', cellWidth: 14 } },
        margin: { top: startY, left: 6, right: 6 }
      });
    });

    this._addFooter(doc);
    return doc.output('arraybuffer');
  }
}

module.exports = PDFExporter;
